# Generated by Django 3.1.4 on 2020-12-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201213_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='NOREGION', max_length=63),
        ),
    ]
